language: scala
scala:
  - 2.12.4
before_install:
  - ./travis/build_api_dependency.sh
script:
  - sbt clean && sbt compile &&
    sbt clean coverage test coverageReport
after_success:
  - sbt coverageReport coveralls
notifications:
  email:
    on_success: never
    on_failure: never